### ISSUE TITLE
Quick question ...

### ISSUE THREAD

**Issue by agwilkinson** [r3volved/CVEAggregate#3]
Hi,

I am really wanting to use this tool, however, i must be missing something because I am struggling to even get started.

For example do I have to create cves.json myself ? If so can you include an example cves.json file ?

Also, is this a tool or a library ? I just need some more thorough docs to even get started.

Thanks!

**Comment by r3volved** [comment]
Heya thanks for interest

To just build the json file, you can run (from cli, with node installed):
```sh
node path/to/folder/build.js path/to/save/cves.json
``` 
If the json file doesn’t exist yet, it will be created. If already exists there, will be updated with changes/additions since last save. 

To leverage in your own node app, it is set up to require the library (i can look towards importing if needed) and instantiate a new CVEAggregate (with optional path to json file - to save/load/update). Currently just writing/loading json to/from disk… (.json file). 

I just sorta wrapped up some of the scripts I use a lot and smashed them into one export class. Also still just poking away at it a little so if there’s anything you think worth adding/changing, let me know or pr me back. Its not intended to be a front end web script since the cve list could get pretty heavy and the sources don’t necessarily allow cors. 

If still not clear, let me know and will try to elaborate further.

**Comment by agwilkinson** [comment]
Hi thanks for the follow up. I get the following error when whether cves.json exists or not.

**> node build.js cves.json**                                                                                                                                                                     
if( !process.argv[2]?.length ) {                                                                                                                                                              
                     ^                                                                                                                                                                                                                                                                                                                                                            
SyntaxError: Unexpected token '.'                                                                                                                                                            
    at wrapSafe (internal/modules/cjs/loader.js:915:16)                                                                                                                                       
    at Module._compile (internal/modules/cjs/loader.js:963:27)                                                                                                                                
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)                                                                                                                 
    at Module.load (internal/modules/cjs/loader.js:863:32)                                                                                                                                    
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)                                                                                                                          
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)                                                                                                       
    at internal/main/run_main_module.js:17:47

**Comment by r3volved** [comment]
I suspect that is your node version not being able to interpret the ?. you probably have < v14. Check version with:
```sh
node —version
``` 
Looks like it should work on 14 and later.
